### ISSUE TITLE
Definir padrões para colaboração

### ISSUE THREAD

**Issue by HenriqueAJNB** [HenriqueAJNB/data-science-escalavel#19]
Definir alguns padrões para colaboração como mensagens de commits seguindo o commit-zen, e outros padrões a serem definidos.

**Comment by joao-vitor-souza** [comment]
Boa. Percebi que os outros PRs não estavam seguindo um padrão então commitei do meu jeito mesmo. Vamos adotar o [commitzen](https://commitizen-tools.github.io/commitizen/) como padrão então? Se sim, já deixa fixado no README para os recém chegados ficarem cientes.
