### ISSUE TITLE
Adicionar dark mode ao jupyter book?

### ISSUE THREAD

**Issue by joao-vitor-souza** [HenriqueAJNB/data-science-escalavel#25]
Para melhorar a acessibilidade e não cansar a vista, podemos adicionar um estilo com dark mode sobre o backend do jupyter book?

Sugestão: [Quantecon Book Theme](https://github.com/QuantEcon/quantecon-book-theme)

No canto superior direito desse [exemplo](https://python-programming.quantecon.org/intro.html) tem um botão que troca para o dark mode.

**Comment by HenriqueAJNB** [comment]
É uma opção bacana! Eu só não pesquisei ainda como faz essa alteração. Chegou a ver algo na documentação sobre como fazer? Posso colocar você como responsável?

**Comment by joao-vitor-souza** [comment]
> É uma opção bacana! Eu só não pesquisei ainda como faz essa alteração. Chegou a ver algo na documentação sobre como fazer? Posso colocar você como responsável?

Pode sim. Essa semana acho que já consigo adicionar esse tema.

**Comment by joao-vitor-souza** [comment]
@HenriqueAJNB, seguinte, existe dois temas com dark mode para o jupyter book. Um deles é o [QuantEcon](https://github.com/QuantEcon/quantecon-book-theme) que eu citei e o segundo é o [Sphinx](https://github.com/pydata/pydata-sphinx-theme). O primeiro tem uma dependência intratável com o pacote do `black`, e o outro só implementou o dark mode na versão `0.8.1`, no entanto o pacote do `jupyter-book` só funciona com esse tema para versões menores que a `0.8.0`. O jeito vai ser esperar a equipe do jupyter book atualizar o pacote para abranger essa atualização.

Essa [aqui](https://pydata-sphinx-theme.readthedocs.io/en/latest/index.html) é a última versão estável do `pydata-sphinx-theme` com dark mode.

Quando o jb atualizar eu reabro esse issue, pode ser?
