### ISSUE TITLE
Erro com o diretório "data" quando rodam "make setup"?

### ISSUE THREAD

**Issue by joao-vitor-souza** [HenriqueAJNB/data-science-escalavel#28]
O template original do cookiecutter tem algumas linhas de git para limpar o cache dentro do target install do Makefile:

```
...
git rm -r --cached 'data/raw'
git rm -r --cached 'data/processed'
git rm -r --cached 'data/final'
git rm -r --cached 'models'
...
```

Pelo menos aqui quando fui rodar essa parte levantou erro de arquivo não encontrado. A nossa tradução removeu essas linha e pelo visto é isso que resolve o problema. Alguém mais teve esse problema?

**Comment by HenriqueAJNB** [comment]
Oi @joao-vitor-souza. O template foi construído pela autora. Vale investigar para sabermos se isso afeta a nossa tradução ou não. Mas creio que é só colocar a opção de force (`-f`) no comando que ele funciona. Qualquer dúvida é só ver na [documentação oficial do git sobre o comando rm](https://git-scm.com/docs/git-rm)

**Comment by joao-vitor-souza** [comment]
> Oi @joao-vitor-souza. O template foi construído pela autora. Vale investigar para sabermos se isso afeta a nossa tradução ou não. Mas creio que é só colocar a opção de force (`-f`) no comando que ele funciona. Qualquer dúvida é só ver na [documentação oficial do git sobre o comando rm](https://git-scm.com/docs/git-rm)

Então, pelo que vi não terá problemas deixar dessa maneira que foi traduzido. A única diferença é que se quisermos rodar novamente o comando `make setup` para talvez reiniciar o projeto, ele não limpará esses diretórios, mas para quem está fazendo a primeira instalação não haverá diferença nenhuma.

**Comment by joao-vitor-souza** [comment]
> Oi @joao-vitor-souza. O template foi construído pela autora. Vale investigar para sabermos se isso afeta a nossa tradução ou não. Mas creio que é só colocar a opção de force (`-f`) no comando que ele funciona. Qualquer dúvida é só ver na [documentação oficial do git sobre o comando rm](https://git-scm.com/docs/git-rm)

Beleza, achei o problema. Essas linhas de código estão na verdade removendo tais diretórios do tracking do GIT, porque depois vamos adicioná-los ao tracking do DVC. 

No livro original a autora não incluiu essas linhas. Acho melhor deixar como está mesmo, fica mais fidedigno à tradução.
