### ISSUE TITLE
Colocar imagem na seção 3.1 de pytest

### ISSUE THREAD

**Issue by HenriqueAJNB** [HenriqueAJNB/data-science-escalavel#5]
Procurar por uma imagem adequada diferente da autora original para colocar no início da seção

**Comment by LevyPy** [comment]
Sugestões:

https://pxhere.com/pt/photo/710477

https://pxhere.com/pt/photo/915011

https://pxhere.com/pt/photo/871995

**Comment by HenriqueAJNB** [comment]
Oi @LevyPy, gostei da 915011! Consegue abrir um PR colocando essa imagem? Já linka com esse issue aqui para encerrarmos ele, por favor?
